@file:Suppress("ReturnCount")

package io.github.reactivecircus.routebinding.compiler.fir

import io.github.reactivecircus.routebinding.compiler.ClassIds
import org.jetbrains.kotlin.GeneratedDeclarationKey
import org.jetbrains.kotlin.descriptors.ClassKind
import org.jetbrains.kotlin.descriptors.Modality
import org.jetbrains.kotlin.descriptors.Visibilities
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.caches.FirCache
import org.jetbrains.kotlin.fir.caches.firCachesFactory
import org.jetbrains.kotlin.fir.declarations.FirDeclarationOrigin
import org.jetbrains.kotlin.fir.declarations.declaredFunctions
import org.jetbrains.kotlin.fir.declarations.getDeprecationsProvider
import org.jetbrains.kotlin.fir.deserialization.toQualifiedPropertyAccessExpression
import org.jetbrains.kotlin.fir.expressions.FirAnnotation
import org.jetbrains.kotlin.fir.expressions.builder.buildAnnotation
import org.jetbrains.kotlin.fir.expressions.builder.buildAnnotationArgumentMapping
import org.jetbrains.kotlin.fir.expressions.builder.buildArgumentList
import org.jetbrains.kotlin.fir.expressions.builder.buildEnumEntryDeserializedAccessExpression
import org.jetbrains.kotlin.fir.expressions.builder.buildGetClassCall
import org.jetbrains.kotlin.fir.expressions.builder.buildLiteralExpression
import org.jetbrains.kotlin.fir.expressions.builder.buildResolvedQualifier
import org.jetbrains.kotlin.fir.extensions.ExperimentalTopLevelDeclarationsGenerationApi
import org.jetbrains.kotlin.fir.extensions.FirDeclarationGenerationExtension
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.extensions.MemberGenerationContext
import org.jetbrains.kotlin.fir.extensions.NestedClassGenerationContext
import org.jetbrains.kotlin.fir.extensions.predicate.LookupPredicate
import org.jetbrains.kotlin.fir.extensions.predicateBasedProvider
import org.jetbrains.kotlin.fir.plugin.createConeType
import org.jetbrains.kotlin.fir.plugin.createConstructor
import org.jetbrains.kotlin.fir.plugin.createMemberFunction
import org.jetbrains.kotlin.fir.plugin.createNestedClass
import org.jetbrains.kotlin.fir.plugin.createTopLevelClass
import org.jetbrains.kotlin.fir.resolve.defaultType
import org.jetbrains.kotlin.fir.resolve.providers.symbolProvider
import org.jetbrains.kotlin.fir.symbols.FirBasedSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirClassLikeSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirClassSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirConstructorSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirNamedFunctionSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.fir.toFirResolvedTypeRef
import org.jetbrains.kotlin.fir.types.builder.buildResolvedTypeRef
import org.jetbrains.kotlin.fir.types.constructClassLikeType
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.Name
import org.jetbrains.kotlin.name.SpecialNames
import org.jetbrains.kotlin.name.StandardClassIds
import org.jetbrains.kotlin.types.ConstantValueKind

/**
 * Generates FIR declaration for the `<NavEntryContent>_NavEntryInstaller` class.
 *
 * Metro IR expects synthetic MetroFactory declarations generated by Metro FIR,
 * using internal `GeneratedDeclarationKey` data objects for lookups.
 * Since FIR code generated by one plugin cannot be processed by other plugin's FIR,
 * we generate the same synthetic `MetroFactory` class in our own FIR using the same
 * `GeneratedDeclarationKey` instances used my Metro FIR so Metro IR can find the declarations.
 *
 * This won't be required once Metro moves factory generation to IR.
 */
@Suppress("TooManyFunctions")
internal class NavEntryInstallerClassGenerator(session: FirSession) : FirDeclarationGenerationExtension(session) {
    private val hasRouteBindingAnnotation = LookupPredicate.create {
        annotated(ClassIds.RouteBinding.Annotation.asSingleFqName())
    }

    private val matchedFunctions: FirCache<Unit, List<FirNamedFunctionSymbol>, Unit> =
        session.firCachesFactory.createCache { _, _ ->
            session.predicateBasedProvider.getSymbolsByPredicate(hasRouteBindingAnnotation)
                .filterIsInstance<FirNamedFunctionSymbol>()
        }

    override fun FirDeclarationPredicateRegistrar.registerPredicates() {
        register(hasRouteBindingAnnotation)
    }

    @ExperimentalTopLevelDeclarationsGenerationApi
    override fun getTopLevelClassIds(): Set<ClassId> {
        return matchedFunctions.getValue(Unit, Unit).map { function ->
            val packageFqName = function.callableId.packageName
            val classNameSuffix = ClassIds.RouteBinding.NavEntryInstaller.shortClassName.asString()
            val className = Name.identifier("${function.name.asString()}_$classNameSuffix")
            ClassId(packageFqName, className)
        }.toSet()
    }

    @ExperimentalTopLevelDeclarationsGenerationApi
    override fun generateTopLevelClassLikeDeclaration(classId: ClassId): FirClassLikeSymbol<*>? {
        return createTopLevelClass(
            classId = classId,
            key = RouteBindingKeys.NavEntryInstallerClassDeclaration,
        ) {
            superType(ClassIds.RouteBinding.NavEntryInstaller.createConeType(session))
        }.apply {
            replaceAnnotations(annotations + buildDeprecatedAnnotation() + buildContributesIntoSetAnnotation())
            replaceDeprecationsProvider(getDeprecationsProvider(session))
        }.symbol
    }

    private fun buildContributesIntoSetAnnotation(): FirAnnotation = buildAnnotation {
        annotationTypeRef = buildResolvedTypeRef {
            coneType = ClassIds.Metro.ContributesIntoSet.createConeType(session)
        }
        argumentMapping = buildAnnotationArgumentMapping {
            mapping[Name.identifier("scope")] = buildAppScopeGetClassCall()
        }
    }

    private fun buildMetroContributionAnnotation(): FirAnnotation = buildAnnotation {
        annotationTypeRef = buildResolvedTypeRef {
            coneType = ClassIds.Metro.MetroContribution.createConeType(session)
        }
        argumentMapping = buildAnnotationArgumentMapping {
            mapping[Name.identifier("scope")] = buildAppScopeGetClassCall()
        }
    }

    private fun buildAppScopeGetClassCall() = buildGetClassCall {
        val appScopeSymbol = session.symbolProvider
            .getClassLikeSymbolByClassId(ClassIds.Metro.AppScope) as FirRegularClassSymbol
        val appScopeConeType = appScopeSymbol.classId.constructClassLikeType()
        val kClassSymbol = session.symbolProvider
            .getClassLikeSymbolByClassId(StandardClassIds.KClass) as FirRegularClassSymbol
        val kClassType = kClassSymbol.classId.constructClassLikeType(arrayOf(appScopeConeType))
        coneTypeOrNull = kClassType
        argumentList = buildArgumentList {
            arguments += buildResolvedQualifier {
                coneTypeOrNull = appScopeConeType
                symbol = appScopeSymbol
                packageFqName = ClassIds.Metro.AppScope.packageFqName
                relativeClassFqName = ClassIds.Metro.AppScope.relativeClassName
                resolvedToCompanionObject = false
            }
        }
    }

    override fun getCallableNamesForClass(classSymbol: FirClassSymbol<*>, context: MemberGenerationContext): Set<Name> {
        return when {
            // for <NavEntryContent>_NavEntryInstaller class
            classSymbol.hasOrigin(RouteBindingKeys.NavEntryInstallerClassDeclaration) ->
                setOf(SpecialNames.INIT, Name.identifier("install"))

            // for nested MetroFactory object
            classSymbol.hasOrigin(RouteBindingKeys.MetroFactoryClassDeclaration) ->
                setOf(SpecialNames.INIT, Name.identifier("create"), Name.identifier("newInstance"))

            // for nested BindsMirror class
            classSymbol.hasOrigin(RouteBindingKeys.BindingMirrorClassDeclaration) ->
                setOf(SpecialNames.INIT)

            else -> emptySet()
        }
    }

    override fun generateConstructors(context: MemberGenerationContext): List<FirConstructorSymbol> {
        val classSymbol = context.owner

        // for <NavEntryContent>_NavEntryInstaller class
        if (classSymbol.hasOrigin(RouteBindingKeys.NavEntryInstallerClassDeclaration)) {
            return listOf(
                createConstructor(
                    owner = classSymbol,
                    key = RouteBindingKeys.Default,
                    isPrimary = true,
                    generateDelegatedNoArgConstructorCall = true,
                ).symbol,
            )
        }

        // for nested MetroFactory object
        if (classSymbol.hasOrigin(RouteBindingKeys.MetroFactoryClassDeclaration)) {
            return listOf(
                createConstructor(
                    owner = classSymbol,
                    key = RouteBindingKeys.Default,
                    isPrimary = true,
                    generateDelegatedNoArgConstructorCall = true,
                    config = { visibility = Visibilities.Private },
                ).symbol,
            )
        }

        // for nested BindsMirror class inside MetroContributionToAppScope
        if (classSymbol.hasOrigin(RouteBindingKeys.BindingMirrorClassDeclaration)) {
            return listOf(
                createConstructor(
                    owner = classSymbol,
                    key = RouteBindingKeys.Default,
                    isPrimary = true,
                    generateDelegatedNoArgConstructorCall = true,
                    config = { visibility = Visibilities.Private },
                ).symbol,
            )
        }

        return emptyList()
    }

    override fun generateFunctions(
        callableId: CallableId,
        context: MemberGenerationContext?,
    ): List<FirNamedFunctionSymbol> {
        if (context == null) return emptyList()
        val classSymbol = context.owner
        val classId = classSymbol.classId

        // install function
        if (classSymbol.hasOrigin(RouteBindingKeys.NavEntryInstallerClassDeclaration)) {
            if (callableId.callableName.asString() != "install") {
                return emptyList()
            }
            return listOf(generateInstallFunction(classSymbol))
        }

        // create and newInstance functions in MetroFactory
        if (classSymbol.hasOrigin(RouteBindingKeys.MetroFactoryClassDeclaration)) {
            val outerClassId = classId.outerClassId!!
            val outerClassType = outerClassId.createConeType(session)
            val factoryType = ClassIds.Metro.Factory.constructClassLikeType(arrayOf(outerClassType))

            return when (callableId.callableName.asString()) {
                "create" -> listOf(
                    createMemberFunction(
                        owner = classSymbol,
                        key = RouteBindingKeys.MetroFactoryCreateFunction,
                        name = Name.identifier("create"),
                        returnType = factoryType,
                    ).symbol,
                )

                "newInstance" -> listOf(
                    createMemberFunction(
                        owner = classSymbol,
                        key = RouteBindingKeys.MetroFactoryNewInstanceFunction,
                        name = Name.identifier("newInstance"),
                        returnType = outerClassType,
                    ).symbol,
                )

                else -> emptyList()
            }
        }

        return emptyList()
    }

    private fun generateInstallFunction(classSymbol: FirClassSymbol<*>): FirNamedFunctionSymbol {
        val navEntryInstallerSymbol = session.symbolProvider
            .getClassLikeSymbolByClassId(ClassIds.RouteBinding.NavEntryInstaller) as FirRegularClassSymbol
        val installFunctionSymbol = navEntryInstallerSymbol.declaredFunctions(session)
            .first { it.name == Name.identifier("install") }

        return createMemberFunction(
            owner = classSymbol,
            key = RouteBindingKeys.InstallFunctionDeclaration,
            name = Name.identifier("install"),
            returnType = installFunctionSymbol.resolvedReturnType,
        ) {
            installFunctionSymbol.contextParameterSymbols.forEach {
                contextReceiver(it.resolvedReturnType)
            }
            installFunctionSymbol.valueParameterSymbols.forEach {
                valueParameter(it.name, it.resolvedReturnType)
            }
            status {
                isOverride = true
            }
        }.symbol
    }

    override fun getNestedClassifiersNames(
        classSymbol: FirClassSymbol<*>,
        context: NestedClassGenerationContext,
    ): Set<Name> {
        return when {
            classSymbol.hasOrigin(RouteBindingKeys.NavEntryInstallerClassDeclaration) ->
                setOf(MetroFactoryName, MetroContributionToAppScopeName)

            classSymbol.hasOrigin(RouteBindingKeys.MetroContributionClassDeclaration) ->
                setOf(BindsMirrorName)

            else -> emptySet()
        }
    }

    override fun generateNestedClassLikeDeclaration(
        owner: FirClassSymbol<*>,
        name: Name,
        context: NestedClassGenerationContext,
    ): FirClassLikeSymbol<*>? {
        if (owner.hasOrigin(RouteBindingKeys.NavEntryInstallerClassDeclaration)) {
            if (name == MetroFactoryName) {
                val ownerType = owner.defaultType()
                val factoryType = ClassIds.Metro.Factory.constructClassLikeType(arrayOf(ownerType))

                return createNestedClass(
                    owner = owner,
                    key = RouteBindingKeys.MetroFactoryClassDeclaration,
                    name = MetroFactoryName,
                    classKind = ClassKind.OBJECT,
                ) {
                    superType(factoryType)
                }.apply {
                    replaceAnnotations(annotations + buildDeprecatedAnnotation())
                    replaceDeprecationsProvider(getDeprecationsProvider(session))
                }.symbol
            }

            if (name == MetroContributionToAppScopeName) {
                return createNestedClass(
                    owner = owner,
                    key = RouteBindingKeys.MetroContributionClassDeclaration,
                    name = MetroContributionToAppScopeName,
                    classKind = ClassKind.INTERFACE,
                ) {
                    modality = Modality.ABSTRACT
                }.apply {
                    val metroContributionAnnotation = buildMetroContributionAnnotation()
                    replaceAnnotations(annotations + buildDeprecatedAnnotation() + metroContributionAnnotation)
                    replaceDeprecationsProvider(getDeprecationsProvider(session))
                }.symbol
            }
        }

        if (owner.hasOrigin(RouteBindingKeys.MetroContributionClassDeclaration) && name == BindsMirrorName) {
            return createNestedClass(
                owner = owner,
                key = RouteBindingKeys.BindingMirrorClassDeclaration,
                name = BindsMirrorName,
                classKind = ClassKind.CLASS,
            ) {
                modality = Modality.ABSTRACT
                // private primary constructor is handled via Default key + Visibilities.Private
            }.apply {
                replaceAnnotations(annotations + buildDeprecatedAnnotation())
                replaceDeprecationsProvider(getDeprecationsProvider(session))
            }.symbol
        }

        return null
    }

    private fun buildDeprecatedAnnotation(): FirAnnotation = buildAnnotation {
        val deprecatedAnnotation = session.symbolProvider
            .getClassLikeSymbolByClassId(StandardClassIds.Annotations.Deprecated) as FirRegularClassSymbol

        annotationTypeRef = deprecatedAnnotation.defaultType().toFirResolvedTypeRef()
        argumentMapping = buildAnnotationArgumentMapping {
            mapping[Name.identifier("message")] = buildLiteralExpression(
                source = null,
                kind = ConstantValueKind.String,
                value = "This synthesized declaration should not be used directly",
                setType = true,
            )
            mapping[Name.identifier("level")] =
                buildEnumEntryDeserializedAccessExpression {
                    enumClassId = StandardClassIds.DeprecationLevel
                    enumEntryName = Name.identifier("HIDDEN")
                }.toQualifiedPropertyAccessExpression(session)
        }
    }

    private fun FirBasedSymbol<*>.hasOrigin(key: GeneratedDeclarationKey): Boolean {
        val origin = origin
        return origin is FirDeclarationOrigin.Plugin && origin.key == key
    }

    companion object {
        private val MetroFactoryName = Name.identifier("MetroFactory")
        private val MetroContributionToAppScopeName = Name.identifier("MetroContributionToAppScope")
        private val BindsMirrorName = Name.identifier("BindsMirror")
    }
}
