@file:Suppress("ReturnCount")

package io.github.reactivecircus.routebinding.compiler.fir

import io.github.reactivecircus.routebinding.compiler.ClassIds
import org.jetbrains.kotlin.descriptors.ClassKind
import org.jetbrains.kotlin.descriptors.Visibilities
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.declarations.getDeprecationsProvider
import org.jetbrains.kotlin.fir.deserialization.toQualifiedPropertyAccessExpression
import org.jetbrains.kotlin.fir.expressions.FirAnnotation
import org.jetbrains.kotlin.fir.expressions.builder.buildAnnotation
import org.jetbrains.kotlin.fir.expressions.builder.buildAnnotationArgumentMapping
import org.jetbrains.kotlin.fir.expressions.builder.buildArgumentList
import org.jetbrains.kotlin.fir.expressions.builder.buildEnumEntryDeserializedAccessExpression
import org.jetbrains.kotlin.fir.expressions.builder.buildGetClassCall
import org.jetbrains.kotlin.fir.expressions.builder.buildLiteralExpression
import org.jetbrains.kotlin.fir.expressions.builder.buildResolvedQualifier
import org.jetbrains.kotlin.fir.extensions.ExperimentalTopLevelDeclarationsGenerationApi
import org.jetbrains.kotlin.fir.extensions.FirDeclarationGenerationExtension
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.extensions.MemberGenerationContext
import org.jetbrains.kotlin.fir.extensions.NestedClassGenerationContext
import org.jetbrains.kotlin.fir.extensions.predicate.LookupPredicate
import org.jetbrains.kotlin.fir.extensions.predicateBasedProvider
import org.jetbrains.kotlin.fir.plugin.createConeType
import org.jetbrains.kotlin.fir.plugin.createConstructor
import org.jetbrains.kotlin.fir.plugin.createMemberFunction
import org.jetbrains.kotlin.fir.plugin.createNestedClass
import org.jetbrains.kotlin.fir.plugin.createTopLevelClass
import org.jetbrains.kotlin.fir.resolve.defaultType
import org.jetbrains.kotlin.fir.resolve.providers.symbolProvider
import org.jetbrains.kotlin.fir.symbols.impl.FirClassLikeSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirClassSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirConstructorSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirNamedFunctionSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.fir.toFirResolvedTypeRef
import org.jetbrains.kotlin.fir.types.builder.buildResolvedTypeRef
import org.jetbrains.kotlin.fir.types.constructClassLikeType
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.Name
import org.jetbrains.kotlin.name.SpecialNames
import org.jetbrains.kotlin.name.StandardClassIds
import org.jetbrains.kotlin.types.ConstantValueKind

/**
 * Generates FIR declaration for the `<NavEntryContent>_NavEntryInstaller` class.
 *
 * Metro IR expects synthetic MetroFactory declarations generated by Metro FIR,
 * using internal `GeneratedDeclarationKey` data objects for lookups.
 * Since FIR code generated by one plugin cannot be processed by other plugin's FIR,
 * we generate the same synthetic `MetroFactory` class in our own FIR using the same
 * `GeneratedDeclarationKey` instances used my Metro FIR so Metro IR can find the declarations.
 *
 * This won't be required once Metro moves factory generation to IR.
 */
@Suppress("TooManyFunctions")
internal class RouteBindingClassGenerator(session: FirSession) : FirDeclarationGenerationExtension(session) {
    private val hasRouteBindingAnnotation = LookupPredicate.create {
        annotated(ClassIds.RouteBinding.Annotation.asSingleFqName())
    }

    private val matchedFunctions by lazy {
        session.predicateBasedProvider.getSymbolsByPredicate(hasRouteBindingAnnotation)
            .filterIsInstance<FirNamedFunctionSymbol>()
    }

    override fun FirDeclarationPredicateRegistrar.registerPredicates() {
        register(hasRouteBindingAnnotation)
    }

    @ExperimentalTopLevelDeclarationsGenerationApi
    override fun getTopLevelClassIds(): Set<ClassId> {
        return matchedFunctions.map { function ->
            val packageFqName = function.callableId.packageName
            val className = Name.identifier("${function.name.asString()}$NavEntryInstallerSuffix")
            ClassId(packageFqName, className)
        }.toSet()
    }

    @ExperimentalTopLevelDeclarationsGenerationApi
    override fun generateTopLevelClassLikeDeclaration(classId: ClassId): FirClassLikeSymbol<*>? {
        if (!classId.shortClassName.asString().endsWith(NavEntryInstallerSuffix)) {
            return null
        }
        return createTopLevelClass(
            classId = classId,
            key = RouteBindingKeys.NavEntryInstallerClassDeclaration,
        ) {
            superType(ClassIds.RouteBinding.NavEntryInstaller.createConeType(session))
        }.apply {
            replaceAnnotations(annotations + buildDeprecatedAnnotation(session) + buildContributesIntoSetAnnotation())
            replaceDeprecationsProvider(getDeprecationsProvider(session))
        }.symbol
    }

    private fun buildContributesIntoSetAnnotation(): FirAnnotation = buildAnnotation {
        annotationTypeRef = buildResolvedTypeRef {
            coneType = ClassIds.Metro.ContributesIntoSet.createConeType(session)
        }
        argumentMapping = buildAnnotationArgumentMapping {
            mapping[Name.identifier("scope")] = buildGetClassCall {
                val appScopeSymbol = session.symbolProvider.getClassLikeSymbolByClassId(ClassIds.Metro.AppScope)!!
                val appScopeConeType = appScopeSymbol.classId.constructClassLikeType()
                val kClassSymbol = session.symbolProvider.getClassLikeSymbolByClassId(StandardClassIds.KClass)!!
                val kClassType = kClassSymbol.classId.constructClassLikeType(arrayOf(appScopeConeType))
                coneTypeOrNull = kClassType
                argumentList = buildArgumentList {
                    arguments += buildResolvedQualifier {
                        coneTypeOrNull = appScopeConeType
                        symbol = appScopeSymbol
                        packageFqName = ClassIds.Metro.AppScope.packageFqName
                        relativeClassFqName = ClassIds.Metro.AppScope.relativeClassName
                        resolvedToCompanionObject = false
                    }
                }
            }
        }
    }

    override fun getCallableNamesForClass(classSymbol: FirClassSymbol<*>, context: MemberGenerationContext): Set<Name> {
        val classId = classSymbol.classId
        // for <NavEntryContent>_NavEntryInstaller class
        if (classId.shortClassName.asString().endsWith(NavEntryInstallerSuffix) && classId.outerClassId == null) {
            return setOf(SpecialNames.INIT, Name.identifier("install"))
        }
        // for nested MetroFactory object
        if (classId.shortClassName == MetroFactoryName &&
            classId.outerClassId?.shortClassName?.asString()?.endsWith(NavEntryInstallerSuffix) == true
        ) {
            return setOf(SpecialNames.INIT, Name.identifier("create"), Name.identifier("newInstance"))
        }
        return emptySet()
    }

    override fun generateConstructors(context: MemberGenerationContext): List<FirConstructorSymbol> {
        val classSymbol = context.owner
        val classId = classSymbol.classId

        // for <NavEntryContent>_NavEntryInstaller class
        if (classId.shortClassName.asString().endsWith(NavEntryInstallerSuffix) && classId.outerClassId == null) {
            return listOf(
                createConstructor(
                    owner = classSymbol,
                    key = RouteBindingKeys.Default,
                    isPrimary = true,
                    generateDelegatedNoArgConstructorCall = true,
                ).symbol,
            )
        }

        // for nested MetroFactory object
        if (classId.shortClassName == MetroFactoryName &&
            classId.outerClassId?.shortClassName?.asString()?.endsWith(NavEntryInstallerSuffix) == true
        ) {
            return listOf(
                createConstructor(
                    owner = classSymbol,
                    key = RouteBindingKeys.Default,
                    isPrimary = true,
                    generateDelegatedNoArgConstructorCall = true,
                    config = { visibility = Visibilities.Private },
                ).symbol,
            )
        }

        return emptyList()
    }

    override fun generateFunctions(
        callableId: CallableId,
        context: MemberGenerationContext?,
    ): List<FirNamedFunctionSymbol> {
        if (context == null) return emptyList()
        val classSymbol = context.owner
        val classId = classSymbol.classId

        // install function
        if (classId.shortClassName.asString().endsWith(NavEntryInstallerSuffix) && classId.outerClassId == null) {
            if (callableId.callableName.asString() != "install") {
                return emptyList()
            }
            return listOf(generateInstallFunction(classSymbol))
        }

        // create and newInstance functions in MetroFactory
        if (classId.shortClassName == MetroFactoryName &&
            classId.outerClassId?.shortClassName?.asString()?.endsWith(NavEntryInstallerSuffix) == true
        ) {
            val outerClassId = classId.outerClassId!!
            val outerClassType = outerClassId.createConeType(session)
            val factoryType = ClassIds.Metro.Factory.constructClassLikeType(arrayOf(outerClassType))

            return when (callableId.callableName.asString()) {
                "create" -> listOf(
                    createMemberFunction(
                        owner = classSymbol,
                        key = RouteBindingKeys.MetroFactoryCreateFunction,
                        name = Name.identifier("create"),
                        returnType = factoryType,
                    ).symbol,
                )
                "newInstance" -> listOf(
                    createMemberFunction(
                        owner = classSymbol,
                        key = RouteBindingKeys.MetroFactoryNewInstanceFunction,
                        name = Name.identifier("newInstance"),
                        returnType = outerClassType,
                    ).symbol,
                )
                else -> emptyList()
            }
        }

        return emptyList()
    }

    private fun generateInstallFunction(classSymbol: FirClassSymbol<*>): FirNamedFunctionSymbol {
        val navKeyType = ClassIds.Nav3.NavKey.createConeType(session)
        val entryProviderScopeType = ClassIds.Nav3.EntryProviderScope.constructClassLikeType(arrayOf(navKeyType))
        val sharedTransitionScopeType = ClassIds.Compose.SharedTransitionScope.createConeType(session)
        val navBackStackType = ClassIds.Nav3.NavBackStack.constructClassLikeType(arrayOf(navKeyType))
        val unitType = session.builtinTypes.unitType.coneType

        return createMemberFunction(
            owner = classSymbol,
            key = RouteBindingKeys.InstallFunctionDeclaration,
            name = Name.identifier("install"),
            returnType = unitType,
        ) {
            contextReceiver(entryProviderScopeType)
            contextReceiver(sharedTransitionScopeType)
            valueParameter(Name.identifier("backStack"), navBackStackType)
            status {
                isOverride = true
            }
        }.symbol
    }

    override fun getNestedClassifiersNames(
        classSymbol: FirClassSymbol<*>,
        context: NestedClassGenerationContext,
    ): Set<Name> {
        if (!classSymbol.classId.shortClassName.asString().endsWith(NavEntryInstallerSuffix)) {
            return emptySet()
        }
        return setOf(MetroFactoryName)
    }

    override fun generateNestedClassLikeDeclaration(
        owner: FirClassSymbol<*>,
        name: Name,
        context: NestedClassGenerationContext,
    ): FirClassLikeSymbol<*>? {
        if (name != MetroFactoryName || !owner.classId.shortClassName.asString().endsWith(NavEntryInstallerSuffix)) {
            return null
        }

        val ownerType = owner.defaultType()
        val factoryType = ClassIds.Metro.Factory.constructClassLikeType(arrayOf(ownerType))

        return createNestedClass(
            owner = owner,
            key = RouteBindingKeys.MetroFactoryClassDeclaration,
            name = MetroFactoryName,
            classKind = ClassKind.OBJECT,
        ) {
            superType(factoryType)
        }.apply {
            replaceAnnotations(annotations + buildDeprecatedAnnotation(session))
            replaceDeprecationsProvider(getDeprecationsProvider(session))
        }.symbol
    }

    private fun buildDeprecatedAnnotation(session: FirSession): FirAnnotation = buildAnnotation {
        val deprecatedAnnotation = session.symbolProvider
            .getClassLikeSymbolByClassId(StandardClassIds.Annotations.Deprecated) as FirRegularClassSymbol

        annotationTypeRef = deprecatedAnnotation.defaultType().toFirResolvedTypeRef()
        argumentMapping = buildAnnotationArgumentMapping {
            mapping[Name.identifier("message")] = buildLiteralExpression(
                source = null,
                kind = ConstantValueKind.String,
                value = "This synthesized declaration should not be used directly",
                setType = true,
            )
            mapping[Name.identifier("level")] =
                buildEnumEntryDeserializedAccessExpression {
                    enumClassId = StandardClassIds.DeprecationLevel
                    enumEntryName = Name.identifier("HIDDEN")
                }.toQualifiedPropertyAccessExpression(session)
        }
    }

    companion object {
        // TODO better way to identify the class being generated?
        private const val NavEntryInstallerSuffix = "_NavEntryInstaller"
        private val MetroFactoryName = Name.identifier("MetroFactory")
    }
}
