

package io.github.reactivecircus.routebinding.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.reactivecircus.routebinding.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("routebinding/routebinding-compiler-plugin/src/test/data/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("routebinding/routebinding-compiler-plugin/src/test/data/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("MixedWithManualBinding.kt")
  public void testMixedWithManualBinding() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/MixedWithManualBinding.kt");
  }

  @Test
  @TestMetadata("MultipleBindingsInMultipleCompilations.kt")
  public void testMultipleBindingsInMultipleCompilations() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/MultipleBindingsInMultipleCompilations.kt");
  }

  @Test
  @TestMetadata("MultipleBindingsInSingleCompilation.kt")
  public void testMultipleBindingsInSingleCompilation() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/MultipleBindingsInSingleCompilation.kt");
  }

  @Test
  @TestMetadata("SameFunctionNameInDifferentPackages.kt")
  public void testSameFunctionNameInDifferentPackages() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/SameFunctionNameInDifferentPackages.kt");
  }

  @Test
  @TestMetadata("SingleBinding.kt")
  public void testSingleBinding() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/SingleBinding.kt");
  }
}
