

package io.github.reactivecircus.routebinding.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.reactivecircus.routebinding.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("routebinding/routebinding-compiler-plugin/src/test/data/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("routebinding/routebinding-compiler-plugin/src/test/data/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("Basic.kt")
  public void testBasic() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/Basic.kt");
  }

  @Test
  @TestMetadata("Multiple.kt")
  public void testMultiple() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/Multiple.kt");
  }

  @Test
  @TestMetadata("NoReceiverAndParams.kt")
  public void testNoReceiverAndParams() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/NoReceiverAndParams.kt");
  }

  @Test
  @TestMetadata("WithBackStackParamOnly.kt")
  public void testWithBackStackParamOnly() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/WithBackStackParamOnly.kt");
  }

  @Test
  @TestMetadata("WithDefaultParam.kt")
  public void testWithDefaultParam() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/WithDefaultParam.kt");
  }

  @Test
  @TestMetadata("WithRouteParamOnly.kt")
  public void testWithRouteParamOnly() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/WithRouteParamOnly.kt");
  }

  @Test
  @TestMetadata("WithSharedTransitionScopeAsContextParam.kt")
  public void testWithSharedTransitionScopeAsContextParam() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/WithSharedTransitionScopeAsContextParam.kt");
  }

  @Test
  @TestMetadata("WithSharedTransitionScopeAsRegularParam.kt")
  public void testWithSharedTransitionScopeAsRegularParam() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/WithSharedTransitionScopeAsRegularParam.kt");
  }
}
