

package io.github.reactivecircus.routebinding.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.reactivecircus.routebinding.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("routebinding/routebinding-compiler-plugin/src/test/data/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  private void run(String fileName) {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/box/" + fileName);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("routebinding/routebinding-compiler-plugin/src/test/data/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("BindingFunctionSignatures.kt")
  public void testBindingFunctionSignatures() {
    run("BindingFunctionSignatures.kt");
  }

  @Test
  @TestMetadata("InstallFunctionCall.kt")
  public void testInstallFunctionCall() {
    run("InstallFunctionCall.kt");
  }

  @Test
  @TestMetadata("ManualBinding.kt")
  public void testManualBinding() {
    run("ManualBinding.kt");
  }

  @Test
  @TestMetadata("MultipleBindingsInMultipleCompilations.kt")
  public void testMultipleBindingsInMultipleCompilations() {
    run("MultipleBindingsInMultipleCompilations.kt");
  }

  @Test
  @TestMetadata("MultipleBindingsInSingleCompilation.kt")
  public void testMultipleBindingsInSingleCompilation() {
    run("MultipleBindingsInSingleCompilation.kt");
  }

  @Test
  @TestMetadata("SameBindingFunctionNameInDifferentPackages.kt")
  public void testSameBindingFunctionNameInDifferentPackages() {
    run("SameBindingFunctionNameInDifferentPackages.kt");
  }

  @Test
  @TestMetadata("SingleBinding.kt")
  public void testSingleBinding() {
    run("SingleBinding.kt");
  }
}
