

package io.github.reactivecircus.routebinding.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.reactivecircus.routebinding.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("routebinding/routebinding-compiler-plugin/src/test/data/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class DiagnosticTestGenerated extends AbstractDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("routebinding/routebinding-compiler-plugin/src/test/data/diagnostic"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("DuplicateParameterType.kt")
  public void testDuplicateParameterType() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/diagnostic/DuplicateParameterType.kt");
  }

  @Test
  @TestMetadata("NonComposableFunction.kt")
  public void testNonComposableFunction() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/diagnostic/NonComposableFunction.kt");
  }

  @Test
  @TestMetadata("NonTopLevelFunction.kt")
  public void testNonTopLevelFunction() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/diagnostic/NonTopLevelFunction.kt");
  }

  @Test
  @TestMetadata("PrivateFunction.kt")
  public void testPrivateFunction() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/diagnostic/PrivateFunction.kt");
  }

  @Test
  @TestMetadata("PublicFunction.kt")
  public void testPublicFunction() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/diagnostic/PublicFunction.kt");
  }

  @Test
  @TestMetadata("UnsupportedContextParameter.kt")
  public void testUnsupportedContextParameter() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/diagnostic/UnsupportedContextParameter.kt");
  }

  @Test
  @TestMetadata("UnsupportedReceiverType.kt")
  public void testUnsupportedReceiverType() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/diagnostic/UnsupportedReceiverType.kt");
  }

  @Test
  @TestMetadata("UnsupportedValueParameter.kt")
  public void testUnsupportedValueParameter() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/diagnostic/UnsupportedValueParameter.kt");
  }
}
