

package io.github.reactivecircus.routebinding.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.reactivecircus.routebinding.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("routebinding/routebinding-compiler-plugin/src/test/data/dump")
@TestDataPath("$PROJECT_ROOT")
public class DumpTestGenerated extends AbstractDumpTest {
  @Test
  public void testAllFilesPresentInDump() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("routebinding/routebinding-compiler-plugin/src/test/data/dump"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("NoReceiverAndParams.kt")
  public void testNoReceiverAndParams() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/NoReceiverAndParams.kt");
  }

  @Test
  @TestMetadata("Standard.kt")
  public void testStandard() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/Standard.kt");
  }

  @Test
  @TestMetadata("WithBackStackParamOnly.kt")
  public void testWithBackStackParamOnly() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/WithBackStackParamOnly.kt");
  }

  @Test
  @TestMetadata("WithParamWithDefaultValue.kt")
  public void testWithParamWithDefaultValue() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/WithParamWithDefaultValue.kt");
  }

  @Test
  @TestMetadata("WithRouteParamOnly.kt")
  public void testWithRouteParamOnly() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/WithRouteParamOnly.kt");
  }

  @Test
  @TestMetadata("WithSharedTransitionScopeAsContextParam.kt")
  public void testWithSharedTransitionScopeAsContextParam() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/WithSharedTransitionScopeAsContextParam.kt");
  }

  @Test
  @TestMetadata("WithSharedTransitionScopeAsValueParam.kt")
  public void testWithSharedTransitionScopeAsValueParam() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/WithSharedTransitionScopeAsValueParam.kt");
  }
}
