

package io.github.reactivecircus.routebinding.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.reactivecircus.routebinding.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("routebinding/routebinding-compiler-plugin/src/test/data/dump")
@TestDataPath("$PROJECT_ROOT")
public class DumpTestGenerated extends AbstractDumpTest {
  private void run(String fileName) {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDump() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("routebinding/routebinding-compiler-plugin/src/test/data/dump"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("NoReceiverAndParams.kt")
  public void testNoReceiverAndParams() {
    run("NoReceiverAndParams.kt");
  }

  @Test
  @TestMetadata("Standard.kt")
  public void testStandard() {
    run("Standard.kt");
  }

  @Test
  @TestMetadata("WithBackStackParamOnly.kt")
  public void testWithBackStackParamOnly() {
    run("WithBackStackParamOnly.kt");
  }

  @Test
  @TestMetadata("WithParamWithDefaultValue.kt")
  public void testWithParamWithDefaultValue() {
    run("WithParamWithDefaultValue.kt");
  }

  @Test
  @TestMetadata("WithRouteParamOnly.kt")
  public void testWithRouteParamOnly() {
    run("WithRouteParamOnly.kt");
  }

  @Test
  @TestMetadata("WithSharedTransitionScopeAsContextParam.kt")
  public void testWithSharedTransitionScopeAsContextParam() {
    run("WithSharedTransitionScopeAsContextParam.kt");
  }

  @Test
  @TestMetadata("WithSharedTransitionScopeAsValueParam.kt")
  public void testWithSharedTransitionScopeAsValueParam() {
    run("WithSharedTransitionScopeAsValueParam.kt");
  }
}
