

package io.github.reactivecircus.routebinding.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.reactivecircus.routebinding.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("routebinding/routebinding-compiler-plugin/src/test/data/diagnostic/ir")
@TestDataPath("$PROJECT_ROOT")
public class IrDiagnosticTestGenerated extends AbstractIrDiagnosticTest {
  @Test
  public void testAllFilesPresentInIr() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("routebinding/routebinding-compiler-plugin/src/test/data/diagnostic/ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }
}
