

package io.github.reactivecircus.routebinding.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.reactivecircus.routebinding.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("routebinding/routebinding-compiler-plugin/src/test/data/dump/ir")
@TestDataPath("$PROJECT_ROOT")
public class IrDumpTestGenerated extends AbstractIrDumpTest {
  @Test
  public void testAllFilesPresentInIr() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("routebinding/routebinding-compiler-plugin/src/test/data/dump/ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("Basic.kt")
  public void testBasic() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/ir/Basic.kt");
  }

  @Test
  @TestMetadata("Minimal.kt")
  public void testMinimal() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/ir/Minimal.kt");
  }

  @Test
  @TestMetadata("WithBackStackParamOnly.kt")
  public void testWithBackStackParamOnly() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/ir/WithBackStackParamOnly.kt");
  }

  @Test
  @TestMetadata("WithDefaultParam.kt")
  public void testWithDefaultParam() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/ir/WithDefaultParam.kt");
  }

  @Test
  @TestMetadata("WithRouteParamOnly.kt")
  public void testWithRouteParamOnly() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/ir/WithRouteParamOnly.kt");
  }

  @Test
  @TestMetadata("WithSharedTransitionScopeReceiverOnly.kt")
  public void testWithSharedTransitionScopeReceiverOnly() {
    runTest("routebinding/routebinding-compiler-plugin/src/test/data/dump/ir/WithSharedTransitionScopeReceiverOnly.kt");
  }
}
