name: "cache-build-logic"
description: "Cache build-logic to fix Configuration Cache restoring issue on GHA. See https://github.com/gradle/actions/issues/21"

runs:
  using: "composite"
  steps:
    - name: Cache build-logic
      uses: actions/cache@v4
      with:
        path: build-logic/build
        key: build-logic-${{ hashFiles('build-logic/src/**', 'build-logic/build.gradle.kts','build-logic/settings.gradle.kts') }}
