

package io.github.reactivecircus.chameleon.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.reactivecircus.chameleon.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("chameleon/chameleon-compiler-plugin/src/test/data/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("chameleon/chameleon-compiler-plugin/src/test/data/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("Basic.kt")
  public void testBasic() {
    runTest("chameleon/chameleon-compiler-plugin/src/test/data/box/Basic.kt");
  }

  @Test
  @TestMetadata("ExistingThemeVariantProperty.kt")
  public void testExistingThemeVariantProperty() {
    runTest("chameleon/chameleon-compiler-plugin/src/test/data/box/ExistingThemeVariantProperty.kt");
  }

  @Test
  @TestMetadata("NoSnapshotFunctionCalls.kt")
  public void testNoSnapshotFunctionCalls() {
    runTest("chameleon/chameleon-compiler-plugin/src/test/data/box/NoSnapshotFunctionCalls.kt");
  }

  @Test
  @TestMetadata("ThemeVariantArgumentProvided.kt")
  public void testThemeVariantArgumentProvided() {
    runTest("chameleon/chameleon-compiler-plugin/src/test/data/box/ThemeVariantArgumentProvided.kt");
  }
}
