

package io.github.reactivecircus.chameleon.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.reactivecircus.chameleon.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("chameleon/chameleon-compiler-plugin/src/test/data/diagnostic/ir")
@TestDataPath("$PROJECT_ROOT")
public class IrDiagnosticTestGenerated extends AbstractIrDiagnosticTest {
  private void run(String fileName) {
    runTest("chameleon/chameleon-compiler-plugin/src/test/data/diagnostic/ir/" + fileName);
  }

  @Test
  public void testAllFilesPresentInIr() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("chameleon/chameleon-compiler-plugin/src/test/data/diagnostic/ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("MissingSnapshotFunction.kt")
  public void testMissingSnapshotFunction() {
    run("MissingSnapshotFunction.kt");
  }

  @Test
  @TestMetadata("MissingThemeVariantEnum.kt")
  public void testMissingThemeVariantEnum() {
    run("MissingThemeVariantEnum.kt");
  }

  @Test
  @TestMetadata("ThemeVariantNotAnEnum.kt")
  public void testThemeVariantNotAnEnum() {
    run("ThemeVariantNotAnEnum.kt");
  }

  @Test
  @TestMetadata("ThemeVariantNotParameterOfSnapshotFunction.kt")
  public void testThemeVariantNotParameterOfSnapshotFunction() {
    run("ThemeVariantNotParameterOfSnapshotFunction.kt");
  }
}
