

package io.github.reactivecircus.chameleon.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.reactivecircus.chameleon.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("chameleon/chameleon-compiler-plugin/src/test/data/ir")
@TestDataPath("$PROJECT_ROOT")
public class IrDumpTestGenerated extends AbstractIrDumpTest {
  @Test
  public void testAllFilesPresentInIr() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("chameleon/chameleon-compiler-plugin/src/test/data/ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("Basic.kt")
  public void testBasic() {
    runTest("chameleon/chameleon-compiler-plugin/src/test/data/ir/Basic.kt");
  }

  @Test
  @TestMetadata("ExisitngThemeVariantProperty.kt")
  public void testExisitngThemeVariantProperty() {
    runTest("chameleon/chameleon-compiler-plugin/src/test/data/ir/ExisitngThemeVariantProperty.kt");
  }

  @Test
  @TestMetadata("NoSnapshotFunctionCalls.kt")
  public void testNoSnapshotFunctionCalls() {
    runTest("chameleon/chameleon-compiler-plugin/src/test/data/ir/NoSnapshotFunctionCalls.kt");
  }

  @Test
  @TestMetadata("ThemeVariantArgumentProvided.kt")
  public void testThemeVariantArgumentProvided() {
    runTest("chameleon/chameleon-compiler-plugin/src/test/data/ir/ThemeVariantArgumentProvided.kt");
  }
}
